%YAML:1.0
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 530.4669406576809, 0., 320.5,
       0.0, 530.4669406576809, 240.5,
       0.0, 0.0, 1.0 ]

distortion_coefficients: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ 0, 0,
       0, 0, 0 ]
